name: CI Pipeline

on: [workflow_dispatch]

jobs:
  log-details:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current Workflow Info
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Workflow Ref Path: ${{ github.workflow_ref }}"
          echo "Unique Run ID: ${{ github.run_id }}"
          echo "Run Sequence Number: ${{ github.run_number }}"
          echo "Workflow: $GITHUB_WORKFLOW"
      - name: Display Workflow
        run: |
          pwd
          cat actionseval/example/.github/workflows/ref.yml@refs/heads/main
