name: CI Pipeline

on: [workflow_dispatch]

jobs:
  log-details:
    runs-on: ubuntu-latest
    steps:
      # - name: Display Current Workflow Info
      #   run: |
      #     echo "Workflow Name: ${{ github.workflow }}"
      #     echo "Workflow Ref Path: ${{ github.workflow_ref }}"
      #     echo "Unique Run ID: ${{ github.run_id }}"
      #     echo "Run Sequence Number: ${{ github.run_number }}"
      #     echo "Workflow: $GITHUB_WORKFLOW"
       - name: Find and print current workflow
         run: |
            workflow_path=$(echo "${{ github.workflow_ref }}" | sed -E 's|[^/]+/[^/]+/(.+)@.*|\1|')
            # cat $workflow_path
            echo "${{ github.workspace }}/$workflow_path"
